spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: roof
      url: jdbc:mysql://localhost:3306/userservice?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
  redis:
    # Redis数据库索引，默认为0
    database: 0
    # Redis服务器地址
    host: 106.13.9.117
    # Redis服务器连接端口
    port: 16379
    # Redis密码，默认为空
    # Redis连接池最大连接数(负值表示没有限制
    jedis:
      pool:
        max-active: 10
        # 连接池最大阻塞等待时间
        max-wait: -1
        # 连接池最大空闲链接
        max-idle: 10
        # 连接池最小空闲链接
        min-idle: 0
    # 链接超时时间
    timeout: 30000
    password: "!@#redis"


# 端口设置
server:
  port: 8763
  servlet:
    session:
      timeout: 600
# 集成Mybatis
mybatis:
  # Mybatis映射
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.javahly.uaaservice.entity

eureka:
  client:
    serviceUrl:
      defaultZone: http://106.13.1.171:8761/eureka/

