
app:
  id: basic-info-service
apollo:
  bootstrap:
    enabled: true
    namespaces: application
  meta: http://106.13.1.171:8080/
  cacheDir: /app/war/apollo/temp/

spring:
  application:
    name: ask-for-leave-service
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: roof
      url: jdbc:mysql://localhost:3306/askforleaveservice?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
  redis:
    # Redis数据库索引，默认为0
    database: 0
    # Redis服务器地址
    host: 106.13.9.117
    # Redis服务器连接端口
    port: 16379
    # Redis密码，默认为空
    password: "!@#redis"
    # Redis连接池最大连接数(负值表示没有限制
    jedis:
      pool:
        max-active: 10
        # 连接池最大阻塞等待时间
        max-wait: -1
        # 连接池最大空闲链接
        max-idle: 10
        # 连接池最小空闲链接
        min-idle: 0
    # 链接超时时间
    timeout: 30000
# 集成Mybatis
mybatis:
  # Mybatis映射
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.javahly.askforleaveservice.entity

# 端口设置
server:
  port: 8083
  servlet.context-path: /v1/leave

# 超时时间配置
feign:
 client:
  config:
   default:
    connectTimeout: 2000
    readTimeout: 3000

swagger:
  apply-default-response-messages: false # 取消使用默认预定义的响应消息,并使用自定义响应消息
  base-package: com.javahly.askforleave.controller
  base-path: /**
  contact:
    email: 1136513099@qq.com
    name: huangliangyun
    url: https://github.com/huangliangyun
  description: Starter for swagger 2.x
  enabled: true
  exclude-path: /error, /ops/**
  global-response-message:
    get:
    - code: 401
      message: 页面不存在
    - code: 500
      message: 系统内部错误
      modelRef: ERROR
    post:
    - code: 500
      message: 系统内部错误
      modelRef: ERROR
  globalOperationParameters:
  - description: 描述
    modelRef: string
    name: name one
    parameterType: header
    required: true
  - description: some description two
    modelRef: string
    name: name two
    parameterType: body
    required: false
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: https://github.com/dyc87112/spring-boot-starter-swagger
  title: 离校申请服务
  version: v1
#eureka:
 #client:
  # serviceUrl:
   # defaultZone: http://106.13.1.171:8761/eureka/
