spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: uaa-route
        uri: lb://uaa-service
        predicates:
        - Path=/uaa-service/**
        filters:
        - StripPrefix=1
      - id: basic-route
        uri: lb://basic-info-service
        predicates:
        - Path=/basic-service/**
        filters:
        - StripPrefix=1


eureka:
 client:
   serviceUrl:
    defaultZone: http://49.233.192.8:8761/eureka/
server:
  port: 8889

app:
  id: sentinel

apollo:
  meta: http://49.233.192.8:8080
  cacheDir: /app/war/apollo/temp/