app:
  id: training-service
apollo:
  bootstrap:
    enabled: true
    namespaces: application
  meta: http://49.233.192.8:8080
  cacheDir: /app/war/apollo/temp/

spring:
  application:
    name: training-service
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: roof
      url: jdbc:mysql://localhost:3306/trainingservice?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
  redis:
    sentinel:
      master: mymaster
      nodes: 106.13.9.117:26379,123.56.219.53:26379,106.13.1.171:26379
    # Redis数据库索引，默认为0
    database: 3
    # Redis服务器地址
    #host: 106.13.9.117
    # Redis服务器连接端口
    #port: 16379
    # Redis密码，默认为空
    password: "!@#redis"
    # Redis连接池最大连接数(负值表示没有限制
    jedis:
      pool:
        max-active: 10
        # 连接池最大阻塞等待时间
        max-wait: -1
        # 连接池最大空闲链接
        max-idle: 10
        # 连接池最小空闲链接
        min-idle: 0
    # 链接超时时间
    timeout: 30000
    # 文件上传
  servlet:
    multipart:
      enabled: true
     #最大支持文件大小
      max-file-size: 100MB
     #最大支持请求大小
      max-request-size: 100MB

# Mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.javahly.trainingservice.entity


eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://49.233.192.8:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

server:
  port: 8083
  servlet:
    session:
      timeout: 600

server.servlet.context-path: /v1/training


rocketmq:
  name-server: 106.13.1.171:9876;
  producer:
    group: transient_producer


#文件存储路径
filepath: D:/file/


tx-lcn:
  client:
   manager-address:  127.0.0.1:9999
  ribbon:
    loadbalancer:
      dtx:
        enabled: true

